version: "2.1"
services:
  postgres:
    image: docker.io/debezium/postgres:12
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
